// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtwekdggqhtvseedekxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0d2VrZGdncWh0dnNlZWRla3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MzE5MTcsImV4cCI6MjA1NDAwNzkxN30.NDenX3gcyn1p5up3Z0QPKon6eaohjrErqSyNCaUZVis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);